//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors : People
    {
        public Authors()
        {
            this.Books = new HashSet<Books>();
        }
    
        public string Bio { get; set; }
    
        public virtual People People { get; set; }
        public virtual ICollection<Books> Books { get; set; }
    }
}
