//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardholders : People
    {
        public Cardholders()
        {
            this.CheckOutLog = new HashSet<CheckOutLog>();
        }
    
        public string Phone { get; set; }
        public string LibraryCardID { get; set; }
    
        public virtual People People { get; set; }
        public virtual ICollection<CheckOutLog> CheckOutLog { get; set; }
    }
}
