//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryInformation2Entities : DbContext
    {
        public LibraryInformation2Entities()
            : base("name=LibraryInformation2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<CheckOutLog> CheckOutLog { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
